Repository raeperd/kickstart.go, pull requests merged in 2024-12, with the labels that each got.

#21 ci: Update coverage reports with coverall
  .github/workflows/build.yaml
  README.md
Labels: documentation, enhancement

#22 test: Add testcase for http middleware
  main_test.go
Labels: enhancement

#26 docs: Fix to add new line after badges
  README.md
Labels: documentation

#25 code suggestion
  main.go
  main_test.go
Labels: enhancement

#33 ci: Fix doker tag error when version string contains `/`
  .github/dependabot.yml
  Makefile
Labels: bug, enhancement
