Repository raeperd/kickstart.go, pull requests merged in 2024-10, with the labels that each got.

#14 docs: Add codecov badge
  README.md
Labels: documentation

#16 fix: Fix shutdown error handling #15
  main.go
Labels: bug, enhancement

#17 refactor: improve `Dockerfile` build process
  Dockerfile
Labels: enhancement

#20 test: Refactor code with smaller lines of codes
  main_test.go
Labels: enhancement
